name: hpo_symb
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gxx_linux-64
  - gcc_linux-64
  - swig
  - pip
  - pandas
  - numpy
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - gplearn
  - sympy
  - xgboost
  - black
  - dill
  - loguru
  - tqdm
  - pip:
    - smac==v2.0.0b1